language: go
go: 
 - release
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
script: go get github.com/constabulary/gb/... && gb build all
notifications:
  email:
    on_success: change
    on_failure: always
